using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Npgsql;

namespace OpenSim.Continuum.Economy
{
    internal sealed class PostgreSqlEconomyStore
    {
        private static readonly ConcurrentDictionary<string, object> s_locks = new(StringComparer.Ordinal);
        internal string ConnectionString { get; }
        internal object SyncRoot { get; }
        internal PostgreSqlEconomyStore(string value)
        {
            if (String.IsNullOrWhiteSpace(value)) throw new ArgumentException("An economy database connection string is required", nameof(value));
            ConnectionString = new NpgsqlConnectionStringBuilder(value).ConnectionString;
            SyncRoot = s_locks.GetOrAdd(ConnectionString, _ => new object());
        }
        internal NpgsqlConnection Open() { NpgsqlConnection c = new(ConnectionString); c.Open(); return c; }
        internal void EnsureSchema() { using NpgsqlConnection c = Open(); EconomySchemaResources.Apply(c, EconomyStorageProvider.PostgreSql); }
        internal void ValidateSchema() { using NpgsqlConnection c = Open(); using NpgsqlCommand q = c.CreateCommand(); q.CommandText = "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=current_schema() AND table_name=ANY(@names)"; q.Parameters.AddWithValue("names", new[] { "continuum_economy_accounts", "continuum_economy_operations", "continuum_economy_transactions", "continuum_economy_adjustments", "continuum_economy_purchases", "continuum_economy_account_registrations" }); if (Convert.ToInt32(q.ExecuteScalar(), CultureInfo.InvariantCulture) != 6) throw new InvalidOperationException("ContinuumEconomy PostgreSQL schema validation failed"); }
        internal static void Add(NpgsqlCommand q, string n, object v) => q.Parameters.AddWithValue(n, v ?? DBNull.Value);
    }

    public sealed class PostgreSqlEconomyLedger : IEconomyLedger
    {
        private readonly PostgreSqlEconomyStore s;
        public PostgreSqlEconomyLedger(string cs) { s = new(cs); }
        internal PostgreSqlEconomyLedger(PostgreSqlEconomyStore store) { s = store; }
        public void EnsureSchema() => s.EnsureSchema(); public void ValidateSchema() => s.ValidateSchema();
        public void EnsureAccount(Guid id) { Valid(id); using NpgsqlConnection c = s.Open(); using NpgsqlCommand q = c.CreateCommand(); q.CommandText = "INSERT INTO continuum_economy_accounts(account_id,balance)VALUES(@id,0)ON CONFLICT(account_id)DO NOTHING"; Add(q, "id", id); q.ExecuteNonQuery(); }
        public bool AccountExists(Guid id) => Scalar(id, "SELECT COUNT(*) FROM continuum_economy_accounts WHERE account_id=@id") != 0;
        public long GetBalance(Guid id) => Scalar(id, "SELECT COALESCE((SELECT balance FROM continuum_economy_accounts WHERE account_id=@id),0)");
        public long GetAvailableBalance(Guid id) => Scalar(id, "SELECT COALESCE((SELECT balance FROM continuum_economy_accounts WHERE account_id=@id),0)-COALESCE((SELECT SUM(amount)FROM continuum_economy_purchases WHERE buyer_id=@id AND state=1),0)");
        public LedgerTransferResult Transfer(LedgerTransferRequest r)
        {
            if (r == null || r.TransactionID == Guid.Empty || r.SenderID == Guid.Empty || r.ReceiverID == Guid.Empty || r.SenderID == r.ReceiverID || r.Amount <= 0 || (r.Description?.Length ?? 0) > 255) return TR(r?.TransactionID ?? Guid.Empty, LedgerResultCode.InvalidRequest, 0, 0, "Invalid transfer request");
            string h = Hash(String.Join("|", r.SenderID, r.ReceiverID, I(r.Amount), r.TransactionType, r.RegionID, r.ObjectID, r.Description ?? String.Empty));
            using NpgsqlConnection c = s.Open(); using NpgsqlTransaction t = c.BeginTransaction(IsolationLevel.Serializable);
            LedgerTransferResult prior = Prior(c, t, r.TransactionID, h); if (prior != null) { t.Commit(); return prior; }
            Ensure(c, t, r.SenderID); Ensure(c, t, r.ReceiverID); Lock(c, t, r.SenderID, r.ReceiverID); long sb = Balance(c, t, r.SenderID), rb = Balance(c, t, r.ReceiverID), held = Held(c, t, r.SenderID);
            if (sb - held < r.Amount) { Insert(c, t, r, h, 2, sb, rb, "Insufficient funds"); t.Commit(); return TR(r.TransactionID, LedgerResultCode.InsufficientFunds, sb, rb, "Insufficient funds"); }
            try { checked { sb -= r.Amount; rb += r.Amount; } }
            catch (OverflowException) { t.Rollback(); return TR(r.TransactionID, LedgerResultCode.InvalidRequest, sb, rb, "The transfer exceeds the supported balance range"); }
            Set(c, t, r.SenderID, sb); Set(c, t, r.ReceiverID, rb); Insert(c, t, r, h, 1, sb, rb, String.Empty); t.Commit(); return TR(r.TransactionID, LedgerResultCode.Committed, sb, rb, "Transfer committed");
        }
        public LedgerAdjustmentResult Adjust(LedgerAdjustmentRequest r)
        {
            if (r == null || r.OperationID == Guid.Empty || r.AccountID == Guid.Empty || r.ActorID == Guid.Empty || r.Amount <= 0 || String.IsNullOrWhiteSpace(r.Reason) || r.Reason.Length > 255 || !Enum.IsDefined(r.Kind) || r.MaximumBalance < 0 || r.DailyCreditLimit < 0 || r.WeeklyCreditLimit < 0 || r.MonthlyCreditLimit < 0) return AR(r?.OperationID ?? Guid.Empty, LedgerResultCode.InvalidRequest, 0, "Invalid adjustment request");
            string h = Hash(String.Join("|", r.AccountID, r.ActorID, I(r.Amount), (int)r.Kind, r.TransactionType, r.Reason, I(r.MaximumBalance), I(r.DailyCreditLimit), I(r.WeeklyCreditLimit), I(r.MonthlyCreditLimit)));
            using NpgsqlConnection c = s.Open(); using NpgsqlTransaction t = c.BeginTransaction(IsolationLevel.Serializable); LedgerAdjustmentResult prior = PriorAdjust(c, t, r.OperationID, h); if (prior != null) { t.Commit(); return prior; }
            Ensure(c, t, r.AccountID); Lock(c, t, r.AccountID); long b = Balance(c, t, r.AccountID); string failure = String.Empty;
            if (r.Kind == LedgerAdjustmentKind.Debit && b - Held(c, t, r.AccountID) < r.Amount) failure = "Insufficient funds";
            if (r.Kind == LedgerAdjustmentKind.Credit) { if (r.MaximumBalance > 0 && (b > r.MaximumBalance || r.Amount > r.MaximumBalance - b)) failure = "Maximum balance exceeded"; DateTime now = DateTime.UtcNow, day = now.Date, week = now.Date.AddDays(-(((int)now.DayOfWeek + 6) % 7)), month = new(now.Year, now.Month, 1, 0, 0, 0, DateTimeKind.Utc); if (failure.Length == 0 && Exceeds(c, t, r.AccountID, r.TransactionType, day, r.DailyCreditLimit, r.Amount)) failure = "Daily credit limit exceeded"; if (failure.Length == 0 && Exceeds(c, t, r.AccountID, r.TransactionType, week, r.WeeklyCreditLimit, r.Amount)) failure = "Weekly credit limit exceeded"; if (failure.Length == 0 && Exceeds(c, t, r.AccountID, r.TransactionType, month, r.MonthlyCreditLimit, r.Amount)) failure = "Monthly credit limit exceeded"; }
            int status = failure.Length == 0 ? 1 : r.Kind == LedgerAdjustmentKind.Debit ? 2 : 3; if (status == 1) { try { checked { b += r.Kind == LedgerAdjustmentKind.Credit ? r.Amount : -r.Amount; } } catch (OverflowException) { t.Rollback(); return AR(r.OperationID, LedgerResultCode.InvalidRequest, b, "The adjustment exceeds the supported balance range"); } Set(c, t, r.AccountID, b); }
            InsertAdjust(c, t, r, h, status, b, failure); t.Commit(); LedgerResultCode code = status == 1 ? LedgerResultCode.Committed : status == 2 ? LedgerResultCode.InsufficientFunds : LedgerResultCode.InvalidRequest; return AR(r.OperationID, code, b, status == 1 ? "Adjustment committed" : failure);
        }
        public IReadOnlyList<LedgerHistoryEntry> GetHistory(Guid id, DateTime? before, int limit)
        {
            Valid(id); if (limit < 1 || limit > 500) throw new ArgumentOutOfRangeException(nameof(limit)); List<LedgerHistoryEntry> list = new(limit * 2); using NpgsqlConnection c = s.Open();
            using (NpgsqlCommand q = c.CreateCommand()) { q.CommandText = "SELECT transaction_id,sender_id,receiver_id,amount,transaction_type,region_id,object_id,description,status,sender_balance,receiver_balance,failure_reason,created_utc FROM continuum_economy_transactions WHERE(sender_id=@id OR receiver_id=@id)AND(CAST(@before AS timestamptz) IS NULL OR created_utc<@before)ORDER BY created_utc DESC,transaction_id DESC LIMIT @limit"; Add(q, "id", id); Add(q, "before", before.HasValue ? before.Value.ToUniversalTime() : DBNull.Value); Add(q, "limit", limit); using NpgsqlDataReader r = q.ExecuteReader(); while (r.Read()) { Guid from = r.GetGuid(1), to = r.GetGuid(2); bool credit = to == id; list.Add(new() { TransactionID = r.GetGuid(0), AccountID = id, CounterpartyID = credit ? from : to, Amount = r.GetInt64(3), TransactionType = r.GetInt32(4), RegionID = r.GetGuid(5), ObjectID = r.GetGuid(6), Description = r.GetString(7), Succeeded = r.GetInt16(8) == 1, ResultingBalance = credit ? r.GetInt64(10) : r.GetInt64(9), FailureReason = r.GetString(11), CreatedUtc = r.GetDateTime(12).ToUniversalTime(), IsCredit = credit }); } }
            using (NpgsqlCommand q = c.CreateCommand()) { q.CommandText = "SELECT operation_id,actor_id,amount,adjustment_kind,transaction_type,reason,status,resulting_balance,failure_reason,created_utc FROM continuum_economy_adjustments WHERE account_id=@id AND(CAST(@before AS timestamptz) IS NULL OR created_utc<@before)ORDER BY created_utc DESC,operation_id DESC LIMIT @limit"; Add(q, "id", id); Add(q, "before", before.HasValue ? before.Value.ToUniversalTime() : DBNull.Value); Add(q, "limit", limit); using NpgsqlDataReader r = q.ExecuteReader(); while (r.Read()) { Guid actor = r.GetGuid(1); list.Add(new() { TransactionID = r.GetGuid(0), AccountID = id, CounterpartyID = actor, ActorID = actor, Amount = r.GetInt64(2), IsCredit = r.GetInt16(3) == 1, TransactionType = r.GetInt32(4), Description = r.GetString(5), Succeeded = r.GetInt16(6) == 1, ResultingBalance = r.GetInt64(7), FailureReason = r.GetString(8), CreatedUtc = r.GetDateTime(9).ToUniversalTime(), IsAdjustment = true }); } }
            list.Sort((a, b) => { int x = b.CreatedUtc.CompareTo(a.CreatedUtc); return x != 0 ? x : b.TransactionID.CompareTo(a.TransactionID); }); if (list.Count > limit) list.RemoveRange(limit, list.Count - limit); return list;
        }
        public long GetCreditedTotal(Guid id, int type, DateTime since) { Valid(id); using NpgsqlConnection c = s.Open(); using NpgsqlCommand q = c.CreateCommand(); q.CommandText = "SELECT COALESCE(SUM(amount),0)FROM continuum_economy_adjustments WHERE account_id=@id AND transaction_type=@type AND adjustment_kind=1 AND status=1 AND created_utc>=@since"; Add(q, "id", id); Add(q, "type", type); Add(q, "since", since.ToUniversalTime()); return Convert.ToInt64(q.ExecuteScalar(), CultureInfo.InvariantCulture); }
        public long CountHistory(Guid id, DateTime? start, DateTime? end) { Valid(id); using NpgsqlConnection c = s.Open(); using NpgsqlCommand q = c.CreateCommand(); q.CommandText = "SELECT(SELECT COUNT(*)FROM continuum_economy_transactions WHERE(sender_id=@id OR receiver_id=@id)AND(CAST(@start AS timestamptz) IS NULL OR created_utc>=@start)AND(CAST(@end AS timestamptz) IS NULL OR created_utc<=@end))+(SELECT COUNT(*)FROM continuum_economy_adjustments WHERE account_id=@id AND(CAST(@start AS timestamptz) IS NULL OR created_utc>=@start)AND(CAST(@end AS timestamptz) IS NULL OR created_utc<=@end))"; Add(q, "id", id); Add(q, "start", start.HasValue ? start.Value.ToUniversalTime() : DBNull.Value); Add(q, "end", end.HasValue ? end.Value.ToUniversalTime() : DBNull.Value); return Convert.ToInt64(q.ExecuteScalar(), CultureInfo.InvariantCulture); }
        public LedgerHistoryEntry GetOperation(Guid id) { if (id == Guid.Empty) throw new ArgumentException("A non-zero operation ID is required", nameof(id)); using NpgsqlConnection c = s.Open(); using (NpgsqlCommand q = c.CreateCommand()) { q.CommandText = "SELECT sender_id,receiver_id,amount,transaction_type,region_id,object_id,description,status,sender_balance,failure_reason,created_utc FROM continuum_economy_transactions WHERE transaction_id=@id"; Add(q, "id", id); using NpgsqlDataReader r = q.ExecuteReader(); if (r.Read()) return new() { TransactionID = id, AccountID = r.GetGuid(0), CounterpartyID = r.GetGuid(1), Amount = r.GetInt64(2), TransactionType = r.GetInt32(3), RegionID = r.GetGuid(4), ObjectID = r.GetGuid(5), Description = r.GetString(6), Succeeded = r.GetInt16(7) == 1, ResultingBalance = r.GetInt64(8), FailureReason = r.GetString(9), CreatedUtc = r.GetDateTime(10).ToUniversalTime() }; } using (NpgsqlCommand q = c.CreateCommand()) { q.CommandText = "SELECT account_id,actor_id,amount,adjustment_kind,transaction_type,reason,status,resulting_balance,failure_reason,created_utc FROM continuum_economy_adjustments WHERE operation_id=@id"; Add(q, "id", id); using NpgsqlDataReader r = q.ExecuteReader(); if (!r.Read()) return null; Guid actor = r.GetGuid(1); return new() { TransactionID = id, AccountID = r.GetGuid(0), CounterpartyID = actor, ActorID = actor, Amount = r.GetInt64(2), IsCredit = r.GetInt16(3) == 1, TransactionType = r.GetInt32(4), Description = r.GetString(5), Succeeded = r.GetInt16(6) == 1, ResultingBalance = r.GetInt64(7), FailureReason = r.GetString(8), CreatedUtc = r.GetDateTime(9).ToUniversalTime(), IsAdjustment = true }; } }
        private long Scalar(Guid id, string sql) { Valid(id); using NpgsqlConnection c = s.Open(); using NpgsqlCommand q = c.CreateCommand(); q.CommandText = sql; Add(q, "id", id); return Convert.ToInt64(q.ExecuteScalar(), CultureInfo.InvariantCulture); }
        private static void Valid(Guid id) { if (id == Guid.Empty) throw new ArgumentException("A non-zero account ID is required"); }
        internal static void Ensure(NpgsqlConnection c, NpgsqlTransaction t, Guid id) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "INSERT INTO continuum_economy_accounts(account_id,balance)VALUES(@id,0)ON CONFLICT(account_id)DO NOTHING"; Add(q, "id", id); q.ExecuteNonQuery(); }
        internal static void Lock(NpgsqlConnection c, NpgsqlTransaction t, params Guid[] ids) { Array.Sort(ids); using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "SELECT account_id FROM continuum_economy_accounts WHERE account_id=ANY(@ids)ORDER BY account_id FOR UPDATE"; Add(q, "ids", ids); using NpgsqlDataReader r = q.ExecuteReader(); while (r.Read()) { } }
        internal static long Balance(NpgsqlConnection c, NpgsqlTransaction t, Guid id) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "SELECT balance FROM continuum_economy_accounts WHERE account_id=@id"; Add(q, "id", id); return Convert.ToInt64(q.ExecuteScalar(), CultureInfo.InvariantCulture); }
        internal static long Held(NpgsqlConnection c, NpgsqlTransaction t, Guid id) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "SELECT COALESCE(SUM(amount),0)FROM continuum_economy_purchases WHERE buyer_id=@id AND state=1"; Add(q, "id", id); return Convert.ToInt64(q.ExecuteScalar(), CultureInfo.InvariantCulture); }
        internal static void Set(NpgsqlConnection c, NpgsqlTransaction t, Guid id, long b) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "UPDATE continuum_economy_accounts SET balance=@b,updated_utc=CURRENT_TIMESTAMP WHERE account_id=@id"; Add(q, "b", b); Add(q, "id", id); if (q.ExecuteNonQuery() != 1) throw new InvalidOperationException("Account update failed"); }
        private static void Insert(NpgsqlConnection c, NpgsqlTransaction t, LedgerTransferRequest r, string h, int status, long sb, long rb, string f) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "INSERT INTO continuum_economy_transactions(transaction_id,request_hash,sender_id,receiver_id,amount,transaction_type,region_id,object_id,description,status,sender_balance,receiver_balance,failure_reason)VALUES(@id,@h,@sender,@receiver,@amount,@type,@region,@object,@description,@status,@sb,@rb,@failure)"; object[] v = { r.TransactionID, h, r.SenderID, r.ReceiverID, r.Amount, r.TransactionType, r.RegionID, r.ObjectID, r.Description ?? String.Empty, status, sb, rb, f }; string[] n = { "id", "h", "sender", "receiver", "amount", "type", "region", "object", "description", "status", "sb", "rb", "failure" }; for (int i = 0; i < n.Length; i++) Add(q, n[i], v[i]); q.ExecuteNonQuery(); }
        private static LedgerTransferResult Prior(NpgsqlConnection c, NpgsqlTransaction t, Guid id, string h) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "SELECT request_hash,status,sender_balance,receiver_balance,failure_reason FROM continuum_economy_transactions WHERE transaction_id=@id"; Add(q, "id", id); using NpgsqlDataReader r = q.ExecuteReader(); if (!r.Read()) return null; if (!String.Equals(r.GetString(0).Trim(), h, StringComparison.Ordinal)) return TR(id, LedgerResultCode.TransactionConflict, 0, 0, "Transaction ID conflict"); int status = r.GetInt16(1); return TR(id, status == 1 ? LedgerResultCode.Replayed : LedgerResultCode.InsufficientFunds, r.GetInt64(2), r.GetInt64(3), status == 1 ? "Transfer already committed" : r.GetString(4)); }
        private static bool Exceeds(NpgsqlConnection c, NpgsqlTransaction t, Guid id, int type, DateTime since, long limit, long amount) { if (limit <= 0) return false; using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "SELECT COALESCE(SUM(amount),0)FROM continuum_economy_adjustments WHERE account_id=@id AND transaction_type=@type AND adjustment_kind=1 AND status=1 AND created_utc>=@since"; Add(q, "id", id); Add(q, "type", type); Add(q, "since", since); return Convert.ToInt64(q.ExecuteScalar(), CultureInfo.InvariantCulture) + amount > limit; }
        private static void InsertAdjust(NpgsqlConnection c, NpgsqlTransaction t, LedgerAdjustmentRequest r, string h, int status, long b, string f) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "INSERT INTO continuum_economy_operations(operation_id,request_hash,operation_kind)VALUES(@id,@h,2);INSERT INTO continuum_economy_adjustments(operation_id,request_hash,account_id,actor_id,amount,adjustment_kind,transaction_type,reason,status,resulting_balance,failure_reason)VALUES(@id,@h,@account,@actor,@amount,@kind,@type,@reason,@status,@balance,@failure)"; object[] v = { r.OperationID, h, r.AccountID, r.ActorID, r.Amount, (short)r.Kind, r.TransactionType, r.Reason, (short)status, b, f }; string[] n = { "id", "h", "account", "actor", "amount", "kind", "type", "reason", "status", "balance", "failure" }; for (int i = 0; i < n.Length; i++) Add(q, n[i], v[i]); q.ExecuteNonQuery(); }
        private static LedgerAdjustmentResult PriorAdjust(NpgsqlConnection c, NpgsqlTransaction t, Guid id, string h) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "SELECT request_hash,status,resulting_balance,failure_reason FROM continuum_economy_adjustments WHERE operation_id=@id"; Add(q, "id", id); using NpgsqlDataReader r = q.ExecuteReader(); if (!r.Read()) return null; if (!String.Equals(r.GetString(0).Trim(), h, StringComparison.Ordinal)) return AR(id, LedgerResultCode.TransactionConflict, 0, "Operation ID conflict"); int status = r.GetInt16(1); LedgerResultCode code = status == 1 ? LedgerResultCode.Replayed : status == 2 ? LedgerResultCode.InsufficientFunds : LedgerResultCode.InvalidRequest; return AR(id, code, r.GetInt64(2), status == 1 ? "Adjustment already committed" : r.GetString(3)); }
        internal static void Add(NpgsqlCommand q, string n, object v) => PostgreSqlEconomyStore.Add(q, n, v); internal static string Hash(string v) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(v))).ToLowerInvariant(); private static string I(long v) => v.ToString(CultureInfo.InvariantCulture); private static LedgerTransferResult TR(Guid id, LedgerResultCode code, long sb, long rb, string m) => new() { TransactionID = id, Code = code, SenderBalance = sb, ReceiverBalance = rb, Message = m }; private static LedgerAdjustmentResult AR(Guid id, LedgerResultCode code, long b, string m) => new() { OperationID = id, Code = code, Balance = b, Message = m };
    }

    public sealed class PostgreSqlEconomyPurchaseService : IEconomyPurchaseService
    {
        private readonly PostgreSqlEconomyStore s; public PostgreSqlEconomyPurchaseService(string cs) { s = new(cs); }
        internal PostgreSqlEconomyPurchaseService(PostgreSqlEconomyStore store) { s = store; }
        public LedgerPurchaseResult Authorize(LedgerPurchaseRequest r) { if (r == null || r.PurchaseID == Guid.Empty || r.BuyerID == Guid.Empty || r.SellerID == Guid.Empty || r.BuyerID == r.SellerID || r.Amount <= 0 || (r.Description?.Length ?? 0) > 255) return R(r?.PurchaseID ?? Guid.Empty, LedgerResultCode.InvalidRequest, 0, 0, 0, 0, "Invalid purchase request"); string h = PostgreSqlEconomyLedger.Hash(String.Join("|", r.BuyerID, r.SellerID, r.Amount.ToString(CultureInfo.InvariantCulture), r.TransactionType, r.RegionID, r.ObjectID, r.Description ?? String.Empty)); using NpgsqlConnection c = s.Open(); using NpgsqlTransaction t = c.BeginTransaction(IsolationLevel.Serializable); Row prior = Read(c, t, r.PurchaseID); if (prior != null) { t.Commit(); return !String.Equals(prior.Hash, h, StringComparison.Ordinal) ? R(r.PurchaseID, LedgerResultCode.TransactionConflict, prior.State, 0, 0, 0, "Purchase ID conflict") : R(r.PurchaseID, LedgerResultCode.Replayed, prior.State, prior.BuyerBalance, prior.BuyerBalance, prior.SellerBalance, "Purchase already recorded"); } PostgreSqlEconomyLedger.Ensure(c, t, r.BuyerID); PostgreSqlEconomyLedger.Ensure(c, t, r.SellerID); PostgreSqlEconomyLedger.Lock(c, t, r.BuyerID, r.SellerID); long bb = PostgreSqlEconomyLedger.Balance(c, t, r.BuyerID), sb = PostgreSqlEconomyLedger.Balance(c, t, r.SellerID), held = PostgreSqlEconomyLedger.Held(c, t, r.BuyerID); int state = bb - held < r.Amount ? 4 : 1; string f = state == 1 ? String.Empty : "Insufficient funds"; using (NpgsqlCommand q = c.CreateCommand()) { q.Transaction = t; q.CommandText = "INSERT INTO continuum_economy_operations(operation_id,request_hash,operation_kind)VALUES(@id,@h,3);INSERT INTO continuum_economy_purchases(purchase_id,request_hash,buyer_id,seller_id,amount,transaction_type,region_id,object_id,description,state,buyer_balance,seller_balance,failure_reason)VALUES(@id,@h,@buyer,@seller,@amount,@type,@region,@object,@description,@state,@bb,@sb,@failure)"; object[] v = { r.PurchaseID, h, r.BuyerID, r.SellerID, r.Amount, r.TransactionType, r.RegionID, r.ObjectID, r.Description ?? String.Empty, (short)state, bb, sb, f }; string[] n = { "id", "h", "buyer", "seller", "amount", "type", "region", "object", "description", "state", "bb", "sb", "failure" }; for (int i = 0; i < n.Length; i++) PostgreSqlEconomyLedger.Add(q, n[i], v[i]); q.ExecuteNonQuery(); } t.Commit(); return R(r.PurchaseID, state == 1 ? LedgerResultCode.Committed : LedgerResultCode.InsufficientFunds, state, bb, bb - held - (state == 1 ? r.Amount : 0), sb, state == 1 ? "Purchase authorized" : f); }
        public LedgerPurchaseResult Capture(Guid id, Guid buyer) => Complete(id, buyer, true); public LedgerPurchaseResult Cancel(Guid id, Guid buyer) => Complete(id, buyer, false);
        private LedgerPurchaseResult Complete(Guid id, Guid expected, bool capture) { if (id == Guid.Empty || expected == Guid.Empty) return R(id, LedgerResultCode.InvalidRequest, 0, 0, 0, 0, "Invalid purchase completion request"); using NpgsqlConnection c = s.Open(); using NpgsqlTransaction t = c.BeginTransaction(IsolationLevel.Serializable); Row r = Read(c, t, id, true); if (r == null) { t.Commit(); return R(id, LedgerResultCode.InvalidRequest, 0, 0, 0, 0, "Purchase not found"); } if (r.Buyer != expected) { t.Commit(); return R(id, LedgerResultCode.InvalidRequest, r.State, r.BuyerBalance, 0, r.SellerBalance, "Purchase buyer mismatch"); } int target = capture ? 2 : 3; if (r.State == target) { t.Commit(); return R(id, LedgerResultCode.Replayed, r.State, r.BuyerBalance, r.BuyerBalance, r.SellerBalance, "Purchase already completed"); } if (r.State != 1) { t.Commit(); return R(id, LedgerResultCode.InvalidRequest, r.State, r.BuyerBalance, 0, r.SellerBalance, "Purchase is not authorized"); } PostgreSqlEconomyLedger.Lock(c, t, r.Buyer, r.Seller); long bb = PostgreSqlEconomyLedger.Balance(c, t, r.Buyer), sb = PostgreSqlEconomyLedger.Balance(c, t, r.Seller); if (capture) { long priorBuyer = bb, priorSeller = sb; try { checked { bb -= r.Amount; sb += r.Amount; } } catch (OverflowException) { t.Rollback(); return R(id, LedgerResultCode.InvalidRequest, r.State, priorBuyer, 0, priorSeller, "The purchase exceeds the supported balance range"); } PostgreSqlEconomyLedger.Set(c, t, r.Buyer, bb); PostgreSqlEconomyLedger.Set(c, t, r.Seller, sb); using NpgsqlCommand tx = c.CreateCommand(); tx.Transaction = t; tx.CommandText = "INSERT INTO continuum_economy_transactions(transaction_id,request_hash,sender_id,receiver_id,amount,transaction_type,region_id,object_id,description,status,sender_balance,receiver_balance)VALUES(@id,@h,@buyer,@seller,@amount,@type,@region,@object,@description,1,@bb,@sb)"; object[] v = { r.ID, r.Hash, r.Buyer, r.Seller, r.Amount, r.Type, r.Region, r.Object, r.Description, bb, sb }; string[] n = { "id", "h", "buyer", "seller", "amount", "type", "region", "object", "description", "bb", "sb" }; for (int i = 0; i < n.Length; i++) PostgreSqlEconomyLedger.Add(tx, n[i], v[i]); tx.ExecuteNonQuery(); } using (NpgsqlCommand q = c.CreateCommand()) { q.Transaction = t; q.CommandText = "UPDATE continuum_economy_purchases SET state=@state,buyer_balance=@bb,seller_balance=@sb,completed_utc=CURRENT_TIMESTAMP WHERE purchase_id=@id AND state=1"; PostgreSqlEconomyLedger.Add(q, "state", (short)target); PostgreSqlEconomyLedger.Add(q, "bb", bb); PostgreSqlEconomyLedger.Add(q, "sb", sb); PostgreSqlEconomyLedger.Add(q, "id", id); if (q.ExecuteNonQuery() != 1) throw new InvalidOperationException("Purchase state changed concurrently"); } t.Commit(); return R(id, LedgerResultCode.Committed, target, bb, bb, sb, capture ? "Purchase captured" : "Purchase cancelled"); }
        public IReadOnlyList<LedgerPendingPurchase> GetPending(DateTime before, int limit) { limit = Math.Clamp(limit, 1, 500); List<LedgerPendingPurchase> list = new(); using NpgsqlConnection c = s.Open(); using NpgsqlCommand q = c.CreateCommand(); q.CommandText = "SELECT purchase_id,buyer_id,seller_id,amount,transaction_type,region_id,object_id,description,created_utc FROM continuum_economy_purchases WHERE state=1 AND created_utc<@before ORDER BY created_utc LIMIT @limit"; PostgreSqlEconomyLedger.Add(q, "before", before.ToUniversalTime()); PostgreSqlEconomyLedger.Add(q, "limit", limit); using NpgsqlDataReader r = q.ExecuteReader(); while (r.Read()) list.Add(new() { PurchaseID = r.GetGuid(0), BuyerID = r.GetGuid(1), SellerID = r.GetGuid(2), Amount = r.GetInt64(3), TransactionType = r.GetInt32(4), RegionID = r.GetGuid(5), ObjectID = r.GetGuid(6), Description = r.GetString(7), CreatedUtc = r.GetDateTime(8).ToUniversalTime() }); return list; }
        private sealed class Row { public Guid ID, Buyer, Seller, Region, Object; public string Hash, Description; public long Amount, BuyerBalance, SellerBalance; public int Type, State; }
        private static Row Read(NpgsqlConnection c, NpgsqlTransaction t, Guid id, bool update = false) { using NpgsqlCommand q = c.CreateCommand(); q.Transaction = t; q.CommandText = "SELECT request_hash,buyer_id,seller_id,amount,transaction_type,region_id,object_id,description,state,buyer_balance,seller_balance FROM continuum_economy_purchases WHERE purchase_id=@id" + (update ? " FOR UPDATE" : String.Empty); PostgreSqlEconomyLedger.Add(q, "id", id); using NpgsqlDataReader r = q.ExecuteReader(); return r.Read() ? new() { ID = id, Hash = r.GetString(0).Trim(), Buyer = r.GetGuid(1), Seller = r.GetGuid(2), Amount = r.GetInt64(3), Type = r.GetInt32(4), Region = r.GetGuid(5), Object = r.GetGuid(6), Description = r.GetString(7), State = r.GetInt16(8), BuyerBalance = r.GetInt64(9), SellerBalance = r.GetInt64(10) } : null; }
        private static LedgerPurchaseResult R(Guid id, LedgerResultCode code, int state, long bb, long available, long sb, string m) => new() { PurchaseID = id, Code = code, State = (LedgerPurchaseState)state, BuyerBalance = bb, BuyerAvailableBalance = available, SellerBalance = sb, Message = m };
    }

    public sealed class PostgreSqlEconomyAccountService : IEconomyAccountService
    {
        private readonly PostgreSqlEconomyStore s; public PostgreSqlEconomyAccountService(string cs) { s = new(cs); }
        internal PostgreSqlEconomyAccountService(PostgreSqlEconomyStore store) { s = store; }
        public LedgerResultCode Register(LedgerAccountRegistrationRequest r, out string message) { if (r == null || r.OperationID == Guid.Empty || r.AccountID == Guid.Empty || r.ActorID == Guid.Empty || (r.AccountType != LedgerAccountType.Group && r.AccountType != LedgerAccountType.System) || String.IsNullOrWhiteSpace(r.DisplayName) || r.DisplayName.Length > 255) { message = "Valid operation, account, actor, non-resident type and display name are required"; return LedgerResultCode.InvalidRequest; } string h = PostgreSqlEconomyLedger.Hash(String.Join("|", r.AccountID, r.ActorID, (int)r.AccountType, r.DisplayName.Trim())); using NpgsqlConnection c = s.Open(); using NpgsqlTransaction t = c.BeginTransaction(IsolationLevel.Serializable); using (NpgsqlCommand prior = c.CreateCommand()) { prior.Transaction = t; prior.CommandText = "SELECT request_hash FROM continuum_economy_account_registrations WHERE operation_id=@id"; PostgreSqlEconomyLedger.Add(prior, "id", r.OperationID); object v = prior.ExecuteScalar(); if (v != null) { t.Commit(); if (!String.Equals(Convert.ToString(v)?.Trim(), h, StringComparison.Ordinal)) { message = "The operation ID is already associated with different registration data"; return LedgerResultCode.TransactionConflict; } message = "Economy account already registered"; return LedgerResultCode.Replayed; } } int? existing = null; using (NpgsqlCommand q = c.CreateCommand()) { q.Transaction = t; q.CommandText = "SELECT account_type FROM continuum_economy_accounts WHERE account_id=@id FOR UPDATE"; PostgreSqlEconomyLedger.Add(q, "id", r.AccountID); object v = q.ExecuteScalar(); if (v != null) existing = Convert.ToInt32(v); } if (existing.HasValue && existing.Value != (int)r.AccountType) { t.Rollback(); message = "The UUID already belongs to a different economy account class"; return LedgerResultCode.TransactionConflict; } using (NpgsqlCommand q = c.CreateCommand()) { q.Transaction = t; q.CommandText = "INSERT INTO continuum_economy_accounts(account_id,balance,account_type)VALUES(@account,0,@type)ON CONFLICT(account_id)DO NOTHING;INSERT INTO continuum_economy_operations(operation_id,request_hash,operation_kind)VALUES(@operation,@hash,4);INSERT INTO continuum_economy_account_registrations(operation_id,request_hash,account_id,actor_id,account_type,display_name)VALUES(@operation,@hash,@account,@actor,@type,@name)"; PostgreSqlEconomyLedger.Add(q, "account", r.AccountID); PostgreSqlEconomyLedger.Add(q, "type", (short)r.AccountType); PostgreSqlEconomyLedger.Add(q, "operation", r.OperationID); PostgreSqlEconomyLedger.Add(q, "hash", h); PostgreSqlEconomyLedger.Add(q, "actor", r.ActorID); PostgreSqlEconomyLedger.Add(q, "name", r.DisplayName.Trim()); q.ExecuteNonQuery(); } t.Commit(); message = "Economy account registered"; return LedgerResultCode.Committed; }
    }
}
